project_name: gcron

before:
  hooks:
    - go mod download

builds:
  -
    main: ./cmd/gcron/main.go 

# - env:
#   - CGO_ENABLED=0
# archives:
# - replacements:
#     darwin: Darwin
#     linux: Linux
#     amd64: x86_64
# checksum:
#   name_template: 'checksums.txt'
# snapshot:
#   name_template: "{{ .Tag }}-next"
# changelog:
#   sort: asc
#   filters:
#     exclude:
#     - '^docs:'
#     - '^test:'
