
server:
    tcp: 
        enabled: false
        host: "localhost"
        port: "1400"
    udp:
        enabled: false
        host: "localhost"
        port: "1401"
    unix: 
        enabled: false
        path: "/tmp/gcron-server.sock"

out:
    hide: 
        systime: false
        usertime: false
        duration: false
        uid: false
    tags: false
    clean: false

log:
    enable: false
    level: "info"
    path: "/var/log/gcron/gcron.log"
