
server:
    tcp: 
        enabled: false
        host: "localhost"
        port: "1400"
    udp:
        enabled: false
        host: "localhost"
        port: "1401"
    unix: 
        enabled: false
        path: "/tmp/gcron-server.sock"

out:
    tags: false
    clean: false

log:
    level: "info"
    path: "./gcron.log"
