
server:
    tcp: 
        enabled: false
        host: "localhost"
        port: "1400"
    udp:
        enabled: false
        host: "localhost"
        port: "1401"
    unix: 
        enabled: true
        path: "/tmp/gcron-server.sock"


log:
    level: "info"
    path: "./gcron.log"
