
server:
    # tcp: 
    #     host: "localhost"
    #     port: "3333"
    # udp:
        # host: "localhost"
        # port: "3334"
    unix: 
        path: "/tmp/gcron-server.sock"


log:
    level: "info"
    path: "/Users/mohamed/www/docker/gcron/gcron.log"
