
server:
    rpc:
        enabled: true
        host: "localhost"
        port: "1402"
    tcp: 
        enabled: false
        host: "localhost"
        port: "1401"
    udp:
        enabled: false
        host: "localhost"
        port: "1402"
    unix: 
        enabled: false
        path: "/tmp/gcron-server.sock"

out:
    hide: 
        systime: false
        usertime: false
        duration: false
        uid: false
    tags: false
    clean: false

log:
    enable: true
    level: "warning"
    path: "/var/log/gcron/gcron.log"
