#!/bin/sh

SCRIPT="gcrond"
RUNAS="root"

PIDFILE=/var/run/gcrond.pid
LOGFILE=/var/log/gcron/gcrond.log

start() {
  if [ -f $PIDFILE ]; then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service ...' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service ...' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac