// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gcron.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	FLock                bool                 `protobuf:"varint,1,opt,name=FLock,proto3" json:"FLock,omitempty"`
	FLockName            string               `protobuf:"bytes,2,opt,name=FLockName,proto3" json:"FLockName,omitempty"`
	FOverride            string               `protobuf:"bytes,3,opt,name=FOverride,proto3" json:"FOverride,omitempty"`
	FDelay               int32                `protobuf:"varint,4,opt,name=FDelay,proto3" json:"FDelay,omitempty"`
	Pid                  int32                `protobuf:"varint,5,opt,name=Pid,proto3" json:"Pid,omitempty"`
	GUID                 string               `protobuf:"bytes,6,opt,name=GUID,proto3" json:"GUID,omitempty"`
	UID                  int32                `protobuf:"varint,7,opt,name=UID,proto3" json:"UID,omitempty"`
	Parent               string               `protobuf:"bytes,8,opt,name=Parent,proto3" json:"Parent,omitempty"`
	Hostname             string               `protobuf:"bytes,9,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	Username             string               `protobuf:"bytes,10,opt,name=Username,proto3" json:"Username,omitempty"`
	Command              string               `protobuf:"bytes,11,opt,name=Command,proto3" json:"Command,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,12,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,13,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	ExitCode             int32                `protobuf:"varint,14,opt,name=ExitCode,proto3" json:"ExitCode,omitempty"`
	Output               string               `protobuf:"bytes,15,opt,name=Output,proto3" json:"Output,omitempty"`
	SystemTime           *timestamp.Timestamp `protobuf:"bytes,16,opt,name=SystemTime,proto3" json:"SystemTime,omitempty"`
	UserTime             *timestamp.Timestamp `protobuf:"bytes,17,opt,name=UserTime,proto3" json:"UserTime,omitempty"`
	Success              bool                 `protobuf:"varint,18,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd548e04c98879c7, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetFLock() bool {
	if m != nil {
		return m.FLock
	}
	return false
}

func (m *Task) GetFLockName() string {
	if m != nil {
		return m.FLockName
	}
	return ""
}

func (m *Task) GetFOverride() string {
	if m != nil {
		return m.FOverride
	}
	return ""
}

func (m *Task) GetFDelay() int32 {
	if m != nil {
		return m.FDelay
	}
	return 0
}

func (m *Task) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Task) GetGUID() string {
	if m != nil {
		return m.GUID
	}
	return ""
}

func (m *Task) GetUID() int32 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *Task) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Task) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Task) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Task) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Task) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Task) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *Task) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *Task) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *Task) GetSystemTime() *timestamp.Timestamp {
	if m != nil {
		return m.SystemTime
	}
	return nil
}

func (m *Task) GetUserTime() *timestamp.Timestamp {
	if m != nil {
		return m.UserTime
	}
	return nil
}

func (m *Task) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Task)(nil), "grpc.Task")
}

func init() {
	proto.RegisterFile("gcron.proto", fileDescriptor_fd548e04c98879c7)
}

var fileDescriptor_fd548e04c98879c7 = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x5f, 0x6f, 0xd3, 0x30,
	0x10, 0x27, 0x6b, 0xfa, 0xef, 0xca, 0xc6, 0xb0, 0xd0, 0x64, 0x45, 0x08, 0xaa, 0x3d, 0xf5, 0x29,
	0x93, 0x06, 0x42, 0xc0, 0x1b, 0xdb, 0x5a, 0x98, 0x54, 0xb1, 0x29, 0xed, 0x78, 0xf7, 0x92, 0x23,
	0xb2, 0x96, 0xc4, 0x91, 0xed, 0x00, 0xe3, 0xf3, 0xf1, 0x39, 0xf8, 0x2c, 0xc8, 0xe7, 0xa6, 0x9b,
	0x98, 0xb4, 0x3e, 0xf4, 0xed, 0x7e, 0x7f, 0xee, 0x7c, 0x77, 0x3a, 0xc3, 0x28, 0x4f, 0xb5, 0xaa,
	0xe2, 0x5a, 0x2b, 0xab, 0x58, 0x98, 0xeb, 0x3a, 0x8d, 0x5e, 0xe5, 0x4a, 0xe5, 0x05, 0x1e, 0x11,
	0x77, 0xdd, 0x7c, 0x3f, 0xfa, 0xa9, 0x45, 0x5d, 0xa3, 0x36, 0xde, 0x15, 0xbd, 0xfe, 0x5f, 0xb7,
	0xb2, 0x44, 0x63, 0x45, 0x59, 0x7b, 0xc3, 0xe1, 0x9f, 0x10, 0xc2, 0xa5, 0x30, 0x37, 0xec, 0x05,
	0x74, 0x67, 0x73, 0x95, 0xde, 0xf0, 0x60, 0x1c, 0x4c, 0x06, 0x89, 0x07, 0xec, 0x25, 0x0c, 0x29,
	0xf8, 0x2a, 0x4a, 0xe4, 0x3b, 0xe3, 0x60, 0x32, 0x4c, 0xee, 0x08, 0x52, 0x2f, 0x7e, 0xa0, 0xd6,
	0x32, 0x43, 0xde, 0x59, 0xa9, 0x2d, 0xc1, 0x0e, 0xa0, 0x37, 0x3b, 0xc3, 0x42, 0xdc, 0xf2, 0x70,
	0x1c, 0x4c, 0xba, 0xc9, 0x0a, 0xb1, 0x7d, 0xe8, 0x5c, 0xca, 0x8c, 0x77, 0x89, 0x74, 0x21, 0x63,
	0x10, 0x7e, 0xbe, 0x3a, 0x3f, 0xe3, 0x3d, 0x2a, 0x41, 0xb1, 0x73, 0x39, 0xaa, 0xef, 0x5d, 0x8e,
	0x39, 0x80, 0xde, 0xa5, 0xd0, 0x58, 0x59, 0x3e, 0x20, 0xdf, 0x0a, 0xb1, 0x08, 0x06, 0x5f, 0x94,
	0xb1, 0x95, 0x6b, 0x71, 0x48, 0xca, 0x1a, 0x3b, 0xed, 0xca, 0xa0, 0x26, 0x0d, 0xbc, 0xd6, 0x62,
	0xc6, 0xa1, 0x7f, 0xaa, 0xca, 0x52, 0x54, 0x19, 0x1f, 0x91, 0xd4, 0x42, 0xf6, 0x1e, 0x86, 0x0b,
	0x2b, 0xb4, 0x5d, 0xca, 0x12, 0xf9, 0xd3, 0x71, 0x30, 0x19, 0x1d, 0x47, 0xb1, 0xdf, 0x64, 0xdc,
	0x6e, 0x32, 0x5e, 0xb6, 0x9b, 0x4c, 0xee, 0xcc, 0xec, 0x2d, 0xf4, 0xa7, 0x55, 0x46, 0x79, 0xbb,
	0x1b, 0xf3, 0x5a, 0xab, 0xeb, 0x72, 0xfa, 0x4b, 0xda, 0x53, 0x95, 0x21, 0xdf, 0xa3, 0x81, 0xd7,
	0xd8, 0x4d, 0x7d, 0xd1, 0xd8, 0xba, 0xb1, 0xfc, 0x99, 0x9f, 0xda, 0x23, 0xf6, 0x11, 0x60, 0x71,
	0x6b, 0x2c, 0x96, 0xf4, 0xd8, 0xfe, 0xc6, 0xc7, 0xee, 0xb9, 0xd9, 0x3b, 0xbf, 0x15, 0xca, 0x7c,
	0xbe, 0x31, 0x73, 0xed, 0x75, 0x1b, 0x5b, 0x34, 0x69, 0x8a, 0xc6, 0x70, 0x46, 0x57, 0xd2, 0xc2,
	0xe3, 0xbf, 0x3b, 0xd0, 0xa5, 0xeb, 0x64, 0x27, 0x10, 0xfa, 0xcb, 0x79, 0x50, 0x71, 0x61, 0xb5,
	0xac, 0xf2, 0x6f, 0xa2, 0x68, 0x30, 0x7a, 0xf8, 0xde, 0x89, 0x52, 0x05, 0x69, 0x87, 0x4f, 0xd8,
	0x14, 0xfa, 0x09, 0x16, 0x28, 0x0c, 0x6e, 0x55, 0x66, 0x0e, 0x7b, 0xe7, 0x95, 0xb4, 0x52, 0x14,
	0xf2, 0x37, 0xd2, 0x91, 0x6f, 0x53, 0xed, 0x13, 0x74, 0xe6, 0x2a, 0xdf, 0xaa, 0xc4, 0x07, 0xd8,
	0x9d, 0xc9, 0xea, 0x5e, 0x3f, 0x10, 0xbb, 0x5f, 0x1c, 0xbb, 0xf8, 0xf1, 0xd4, 0xeb, 0x1e, 0xb1,
	0x6f, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x53, 0xef, 0x4a, 0x96, 0x04, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GcronClient is the client API for Gcron service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GcronClient interface {
	// Lock remote lock based on (HOSTNAME+USERNAME+UID) or Custom Lock Name
	Lock(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
	// Release release lock based on (HOSTNAME+USERNAME+UID) or Custom Lock Name
	Release(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
	InitializeTask(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
	Log(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
	FinializeTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
}

type gcronClient struct {
	cc grpc.ClientConnInterface
}

func NewGcronClient(cc grpc.ClientConnInterface) GcronClient {
	return &gcronClient{cc}
}

func (c *gcronClient) Lock(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, "/grpc.gcron/Lock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gcronClient) Release(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, "/grpc.gcron/Release", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gcronClient) InitializeTask(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, "/grpc.gcron/InitializeTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gcronClient) Log(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, "/grpc.gcron/Log", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gcronClient) FinializeTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, "/grpc.gcron/FinializeTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GcronServer is the server API for Gcron service.
type GcronServer interface {
	// Lock remote lock based on (HOSTNAME+USERNAME+UID) or Custom Lock Name
	Lock(context.Context, *wrappers.StringValue) (*wrappers.BoolValue, error)
	// Release release lock based on (HOSTNAME+USERNAME+UID) or Custom Lock Name
	Release(context.Context, *wrappers.StringValue) (*wrappers.BoolValue, error)
	InitializeTask(context.Context, *wrappers.StringValue) (*wrappers.BoolValue, error)
	Log(context.Context, *wrappers.StringValue) (*wrappers.BoolValue, error)
	FinializeTask(context.Context, *Task) (*wrappers.BoolValue, error)
}

// UnimplementedGcronServer can be embedded to have forward compatible implementations.
type UnimplementedGcronServer struct {
}

func (*UnimplementedGcronServer) Lock(ctx context.Context, req *wrappers.StringValue) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lock not implemented")
}
func (*UnimplementedGcronServer) Release(ctx context.Context, req *wrappers.StringValue) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Release not implemented")
}
func (*UnimplementedGcronServer) InitializeTask(ctx context.Context, req *wrappers.StringValue) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitializeTask not implemented")
}
func (*UnimplementedGcronServer) Log(ctx context.Context, req *wrappers.StringValue) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Log not implemented")
}
func (*UnimplementedGcronServer) FinializeTask(ctx context.Context, req *Task) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinializeTask not implemented")
}

func RegisterGcronServer(s *grpc.Server, srv GcronServer) {
	s.RegisterService(&_Gcron_serviceDesc, srv)
}

func _Gcron_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GcronServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gcron/Lock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GcronServer).Lock(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gcron_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GcronServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gcron/Release",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GcronServer).Release(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gcron_InitializeTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GcronServer).InitializeTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gcron/InitializeTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GcronServer).InitializeTask(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gcron_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GcronServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gcron/Log",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GcronServer).Log(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gcron_FinializeTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GcronServer).FinializeTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gcron/FinializeTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GcronServer).FinializeTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gcron_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gcron",
	HandlerType: (*GcronServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lock",
			Handler:    _Gcron_Lock_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _Gcron_Release_Handler,
		},
		{
			MethodName: "InitializeTask",
			Handler:    _Gcron_InitializeTask_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _Gcron_Log_Handler,
		},
		{
			MethodName: "FinializeTask",
			Handler:    _Gcron_FinializeTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gcron.proto",
}
