
server:
    web:
        host: "localhost"
        port: "1401"
    rpc: 
        host: "localhost"
        port: "1400"
db: 
    dataDir: "./data"

log:
    enable: false
    level: "info"
    path: "/var/log/gcron/gcrond.log"

web: 
    static: "web/static"
    auth:
        user: "admin"
        pass: "admin"